### ISSUE TITLE
Feature Request: include video files

### ISSUE THREAD

**Issue by mmzoo** [gergelysanta/PhotoMiner#23]
It took me quite some time to find an app exactly like this. I'm glad I found it. Thank you for the hard work you put into this.

I just wanted to ask how difficult it would be to include video files as well? Right now, I organize all photos, taken with several different devices, but when I'm done, I still have to sort all video files manually. These are mp4 (etc.) files that were taken with the same camera/mobile phone.

**Comment by gergelysanta** [comment]
Thanks for the suggestion. Finding also video files wouldn't be too difficult. Displaying them maybe a bit more. Anyhow, this is a good idea to implement, thanks.

**Comment by gergelysanta** [comment]
Feature implemented, will be included in next release.

**Comment by mmzoo** [comment]
![](https://media.giphy.com/media/UMhEPGuoL1zW/giphy.gif)
