### ISSUE TITLE
Remove (or ignore) images that were moved to another folder

### ISSUE THREAD

**Issue by halo** [gergelysanta/PhotoMiner#26]
I often drag a number of sequential images out of PhotoMiner into a separate folder (such as 10 images of event A or 5 images of event B).

The problem is this:

* The images remain visible in PhotoMiner
* I cannot drag/move any other images, if one of those moved-away images happens to be selected

I'm not sure whether this is a feature or a bug though :) Could you give me a hint?

I'd expect images that were dragged out to be hidden from the collection just as deleting images makes them disappear.

PS: As a side note, I often find myself clicking on one image, holding shift, and clicking on a second image, wanting to select all images in between (just like Finder does). But only the two individual images get selected.

**Comment by gergelysanta** [comment]
Yes, this is a bug, thanks for reporting. And sorry for the delay with my response...

**Comment by gergelysanta** [comment]
The default Shift+Click behavior for icons grid is the same as for Cmd+Click. Finder also selects range of files only when switched to list view. In icon grid view Shift+Click doesn't select range of files even there. Unfortunately it doesn't seems to be achievable in collection view.

**Comment by halo** [comment]
> And sorry for the delay with my response

You're an open source maintainer, you should never have to say sorry 😄 Thank you for the bugfix!

> Finder also selects range of files only when switched to list view

Thank you very much for your feedback. It all makes sense now. You are totally right!
